In [4]:
import os

print(os.getcwd())
import os

print(os.listdir())

c:\Users\chitrashree\myenv\PythonPrograms\Python_programs_1\ML
['data_cleanaing.ipynb', 'height_weight.csv', 'polynomial_Regression.ipynb', 'Ridge Lassso Elastic Regression Practicals', 'simple_linear_Regression.ipynb']

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(
    "Ridge Lassso Elastic Regression Practicals/Algerian_forest_fires_dataset_UPDATE.csv"
)

df.head(20)

                                                                      Bejaia Region Dataset
day month year Temperature  RH  Ws Rain  FFMC DMC  DC   ISI BUI  FWI               Classes
01  06    2012 29          57  18  0     65.7 3.4  7.6  1.3 3.4  0.5             not fire
02  06    2012 29          61  13  1.3   64.4 4.1  7.6  1   3.9  0.4             not fire
03  06    2012 26          82  22  13.1  47.1 2.5  7.1  0.3 2.7  0.1             not fire
04  06    2012 25          89  13  2.5   28.6 1.3  6.9  0   1.7  0               not fire
05  06    2012 27          77  16  0     64.8 3    14.2 1.2 3.9  0.5             not fire
06  06    2012 31          67  14  0     82.6 5.8  22.2 3.1 7    2.5                 fire
07  06    2012 33          54  13  0     88.2 9.9  30.5 6.4 10.9 7.2                 fire
08  06    2012 30          73  15  0     86.6 12.1 38.3 5.6 13.5 7.1                 fire
09  06    2012 25          88  13  0.2   52.9 7.9  38.8 0.4 10.5 0.3             not fire
10  06    2012 28          79  12  0     73.2 9.5  46.3 1.3 12.6 0.9             not fire
11  06    2012 31          65  14  0     84.5 12.5 54.3 4   15.8 5.6                 fire
12  06    2012 26          81  19  0     84   13.8 61.4 4.8 17.7 7.1                 fire
13  06    2012 27          84  21  1.2   50   6.7  17   0.5 6.7  0.2             not fire
14  06    2012 30          78  20  0.5   59   4.6  7.8  1   4.4  0.4             not fire
15  06    2012 28          80  17  3.1   49.4 3    7.4  0.4 3    0.1             not fire
16  06    2012 29          89  13  0.7   36.1 1.7  7.6  0   2.2  0               not fire
17  06    2012 30          89  16  0.6   37.3 1.1  7.8  0   1.6  0               not fire
18  06    2012 31          78  14  0.3   56.9 1.9  8    0.7 2.4  0.2             not fire
19  06    2012 31          55  16  0.1   79.9 4.5  16   2.5 5.3  1.4             not fire

In [18]:
df.info()

<class 'pandas.DataFrame'>
MultiIndex: 247 entries, ('day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI') to ('30', '09', '2012', '24', '64', '15', '0.2', '67.3', '3.8', '16.5', '1.2', '4.8', '0.5')
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bejaia Region Dataset   245 non-null    str
dtypes: str(1)
memory usage: 15.3+ KB

In [19]:
df.isnull()

                                                                     Bejaia Region Dataset
day month year Temperature  RH  Ws Rain  FFMC DMC DC   ISI BUI  FWI                   False
01  06    2012 29          57  18  0     65.7 3.4 7.6  1.3 3.4  0.5                   False
02  06    2012 29          61  13  1.3   64.4 4.1 7.6  1   3.9  0.4                   False
03  06    2012 26          82  22  13.1  47.1 2.5 7.1  0.3 2.7  0.1                   False
04  06    2012 25          89  13  2.5   28.6 1.3 6.9  0   1.7  0                     False
...                                                                                     ...
26  09    2012 30          65  14  0     85.4 16  44.5 4.5 16.9 6.5                   False
27  09    2012 28          87  15  4.4   41.1 6.5 8    0.1 6.2  0                     False
28  09    2012 27          87  29  0.5   45.9 3.5 7.9  0.4 3.4  0.2                   False
29  09    2012 24          54  18  0.1   79.7 4.3 15.2 1.7 5.1  0.7                   False
30  09    2012 24          64  15  0.2   67.3 3.8 16.5 1.2 4.8  0.5                   False

[247 rows x 1 columns]

In [20]:
df.dropna(inplace=True)
df.head()

                                                                  Bejaia Region Dataset
day month year Temperature  RH  Ws Rain  FFMC DMC DC  ISI BUI FWI              Classes
01  06    2012 29          57  18  0     65.7 3.4 7.6 1.3 3.4 0.5            not fire
02  06    2012 29          61  13  1.3   64.4 4.1 7.6 1   3.9 0.4            not fire
03  06    2012 26          82  22  13.1  47.1 2.5 7.1 0.3 2.7 0.1            not fire
04  06    2012 25          89  13  2.5   28.6 1.3 6.9 0   1.7 0              not fire

In [22]:
import pandas as pd

df = pd.read_csv(
    "Ridge Lassso Elastic Regression Practicals/Algerian_forest_fires_dataset_UPDATE.csv",
    skiprows=1
)

print(df.head())
print(df.columns)

  day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0  01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5
1  02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4
2  03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1
3  04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0
4  05    06  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5

     Classes
0  not fire
1  not fire
2  not fire
3  not fire
4  not fire
Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  '],
      dtype='str')

In [23]:
print(df.columns)

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  '],
      dtype='str')

In [24]:
#fix spaces in columns names
df.columns=df.columns.str.strip()
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes'],
      dtype='str')

In [27]:
#change the datatypes
 
df[['day','month','year','Temperature','RH','Ws']] = df[
    ['day','month','year','Temperature','RH','Ws']
].astype(int)

ValueError: invalid literal for int() with base 10: 'Sidi-Bel Abbes Region Dataset'

In [28]:
print(df[['day','month','year','Temperature','RH','Ws']].head(20))

   day month  year Temperature  RH  Ws
0   01    06  2012          29  57  18
1   02    06  2012          29  61  13
2   03    06  2012          26  82  22
3   04    06  2012          25  89  13
4   05    06  2012          27  77  16
5   06    06  2012          31  67  14
6   07    06  2012          33  54  13
7   08    06  2012          30  73  15
8   09    06  2012          25  88  13
9   10    06  2012          28  79  12
10  11    06  2012          31  65  14
11  12    06  2012          26  81  19
12  13    06  2012          27  84  21
13  14    06  2012          30  78  20
14  15    06  2012          28  80  17
15  16    06  2012          29  89  13
16  17    06  2012          30  89  16
17  18    06  2012          31  78  14
18  19    06  2012          31  55  16
19  20    06  2012          30  80  16

In [29]:
print(df.iloc[122])

day            Sidi-Bel Abbes Region Dataset
month                                    NaN
year                                     NaN
Temperature                              NaN
RH                                       NaN
Ws                                       NaN
Rain                                     NaN
FFMC                                     NaN
DMC                                      NaN
DC                                       NaN
ISI                                      NaN
BUI                                      NaN
FWI                                      NaN
Classes                                  NaN
Name: 122, dtype: str

In [30]:
#drop NaN values
df = df.drop(index=122)

In [34]:
df.reset_index(drop=True, inplace=True)
##Resetting the index

In [36]:
df = df[df['day'] != 'day']
df.reset_index(drop=True, inplace=True)

In [37]:
# now change the datatypes
 
df[['day','month','year','Temperature','RH','Ws']] = df[
    ['day','month','year','Temperature','RH','Ws']
].astype(int)

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    int64
 1   month        244 non-null    int64
 2   year         244 non-null    int64
 3   Temperature  244 non-null    int64
 4   RH           244 non-null    int64
 5   Ws           244 non-null    int64
 6   Rain         244 non-null    str
 7   FFMC         244 non-null    str
 8   DMC          244 non-null    str
 9   DC           244 non-null    str
 10  ISI          244 non-null    str
 11  BUI          244 non-null    str
 12  FWI          244 non-null    str
 13  Classes      243 non-null    str
dtypes: int64(6), str(8)
memory usage: 26.8 KB

In [43]:
#changing othe columns to float 
[col for col in df.columns if df[col].dtype == 'str']

['Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes']

In [54]:
cols = ['Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI']

for col in cols:
    df[col] = df[col].astype(str).str.strip()
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [55]:
#drop day,month and year as they are not required for regression
df_copy=df.drop(['day','month','year'],axis=1)