In [2]:
#using dataset from tips
import seaborn as sns 

df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [4]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [5]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [6]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [7]:
#feature encoding
#independent and dependent features
X=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y=df['total_bill']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
X_train.head()

      tip   sex smoker   day    time  size
228  2.72  Male     No   Sat  Dinner     2
208  2.03  Male    Yes   Sat  Dinner     2
96   4.00  Male    Yes   Fri  Dinner     2
167  4.50  Male     No   Sun  Dinner     4
84   2.03  Male     No  Thur   Lunch     2

In [33]:
print(X_train['sex'].head())
print(X_test['sex'].head())
print(le_sex.classes_)

228    1
208    1
96     1
167    1
84     1
Name: sex, dtype: int64
24       Male
6        Male
153      Male
211      Male
198    Female
Name: sex, dtype: category
Categories (2, str): ['Male', 'Female']
[0 1]

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_sex = LabelEncoder()
le_smoker = LabelEncoder()
le_day = LabelEncoder()
le_time = LabelEncoder()

X_train['sex'] = le_sex.fit_transform(X_train['sex'])
X_test['sex'] = le_sex.transform(X_test['sex'])

X_train['smoker'] = le_smoker.fit_transform(X_train['smoker'])
X_test['smoker'] = le_smoker.transform(X_test['smoker'])

X_train['day'] = le_day.fit_transform(X_train['day'])
X_test['day'] = le_day.transform(X_test['day'])

X_train['time'] = le_time.fit_transform(X_train['time'])
X_test['time'] = le_time.transform(X_test['time'])

ValueError: invalid literal for int() with base 10: 'Male'

In [13]:
X_train['sex']

228    1
208    1
96     1
167    1
84     1
      ..
106    1
14     0
92     0
179    1
102    0
Name: sex, Length: 195, dtype: int64

In [14]:
X_test.head()

      tip     sex smoker   day    time  size
24   3.18    Male     No   Sat  Dinner     2
6    2.00    Male     No   Sun  Dinner     2
153  2.00    Male     No   Sun  Dinner     4
211  5.16    Male    Yes   Sat  Dinner     4
198  2.00  Female    Yes  Thur   Lunch     2

In [20]:
X_train

      tip  sex  smoker   day  time  size
228  2.72    1       0   Sat     0     2
208  2.03    1       1   Sat     0     2
96   4.00    1       1   Fri     0     2
167  4.50    1       0   Sun     0     4
84   2.03    1       0  Thur     1     2
..    ...  ...     ...   ...   ...   ...
106  4.06    1       1   Sat     0     2
14   3.02    0       0   Sun     0     2
92   1.00    0       1   Fri     0     2
179  3.55    1       1   Sun     0     2
102  2.50    0       1   Sat     0     3

[195 rows x 6 columns]

In [24]:
print(X_train.select_dtypes(include='object').columns)

Index([], dtype='str')

In [25]:
print(X_train.head())

      tip  sex  smoker   day  time  size
228  2.72    1       0   Sat     0     2
208  2.03    1       1   Sat     0     2
96   4.00    1       1   Fri     0     2
167  4.50    1       0   Sun     0     4
84   2.03    1       0  Thur     1     2

In [26]:
print(X_train.dtypes)

tip        float64
sex          int64
smoker       int64
day       category
time         int64
size         int64
dtype: object

In [27]:
from sklearn.preprocessing import LabelEncoder

le_day = LabelEncoder()

X_train['day'] = le_day.fit_transform(X_train['day'])
X_test['day'] = le_day.transform(X_test['day'])

In [28]:
from sklearn.svm import SVR

svr = SVR()
svr.fit(X_train, y_train)

SVR()

In [29]:
y_pred=svr.predict(X_test)

ValueError: could not convert string to float: 'Male'