In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

df = pd.read_excel(
    r"C:\Users\chitrashree\myenv\PythonPrograms\Python_programs_1\flight_price.xlsx"
)

print(df.head())

       Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897
1    05:50         13:15   7h 25m     2 stops         No info   7662
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882
3    18:05         23:30   5h 25m      1 stop         No info   6218
4    16:50         21:35   4h 45m      1 stop         No info  13302

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [7]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [17]:
df['Date']=df['Date_of_Journey'].str.split('/').str[0]
df[['Date_of_Journey', 'Date']].head()

df['Month']=df['Date_of_Journey'].str.split('/').str[1]
df[['Date_of_Journey', 'Month']].head()

  Date_of_Journey Month
0      24/03/2019    03
1       1/05/2019    05
2       9/06/2019    06
3      12/05/2019    05
4      01/03/2019    03

In [24]:
#converting the datatype
df['Date']=df['Date'].astype(int)
df['Date'].head()
df['Month']=df['Month'].astype(int)
df['Month'].head()

0    3
1    5
2    6
3    5
4    3
Name: Month, dtype: int64

In [32]:
df['Arrival_min']=df['Arrival_Time'].str.split(':').str[0]
df[['Arrival_Time', 'Arrival_min']].head()

  Arrival_Time Arrival_min
0           01          01
1           13          13
2           04          04
3           23          23
4           21          21

In [ ]:
#using lambda function
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(': ')[0])
df[['Arrival_Time']].head()

  Arrival_Time
0           01
1           13
2           04
3           23
4           21

In [ ]:
df.head()
#here extra 4 colums we added taht is arrival_hour and arrival_min and date and hour

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Arrival_hour,Arrival_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01,2h 50m,non-stop,No info,3897,24,3,01,01
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13,7h 25m,2 stops,No info,7662,1,5,13,13
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04,19h,2 stops,No info,13882,9,6,04,04
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23,5h 25m,1 stop,No info,6218,12,5,23,23
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21,4h 45m,1 stop,No info,13302,1,3,21,21

In [44]:
#remove the Arrival_time column
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Arrival_hour,Arrival_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,01,01
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,13,13
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,04,04
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,23,23
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,21,21

In [51]:
df['Dep_hour'] = df['Dep_Time'].str.split(':').str[0]
df[['Dep_Time', 'Dep_hour']].head()

df['Dep_min'] = df['Dep_Time'].str.split(':').str[0]
df[['Dep_Time', 'Dep_min']].head()

#checking if columns are added
df.head(3)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,01,01,22,22
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,13,13,05,05
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,04,04,09,09

In [54]:
#checking the datatype and converting accordingly to int
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Duration         10683 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10683 non-null  str
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Arrival_hour     10683 non-null  object
 13  Arrival_min      10683 non-null  object
 14  Dep_hour         10683 non-null  object
 15  Dep_min          10683 non-null  object
dtypes: int64(3), object(4), str(9)
memory usage: 1.3+ MB

In [56]:
#converting object types to int
df['Arrival_hour']=df['Arrival_hour'].astype(int)
df['Arrival_min']=df['Arrival_min'].astype(int)
df['Dep_hour']=df['Dep_hour'].astype(int)
df['Dep_min']=df['Dep_min'].astype(int)

In [ ]:
df.info()
#we can see that everything is converted to int

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Duration         10683 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10683 non-null  str
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Arrival_hour     10683 non-null  int64
 13  Arrival_min      10683 non-null  int64
 14  Dep_hour         10683 non-null  int64
 15  Dep_min          10683 non-null  int64
dtypes: int64(7), str(9)
memory usage: 1.3 MB

In [64]:
#checking for NaN values and filling the data
df.isnull().sum()

#replacing Null valueprint(df['Total_Stops'].dtype)
print(df['Total_Stops'].dtype)
print(df['Total_Stops'].head())

df['Total_Stops'] = df['Total_Stops'].fillna('0')

str
0    non-stop
1     2 stops
2     2 stops
3      1 stop
4      1 stop
Name: Total_Stops, dtype: str